/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:UI[3];

//Textdraws
UI[0] = TextDrawCreate(267.000000, 5.000000, "Legacy");
TextDrawFont(UI[0], 0);
TextDrawLetterSize(UI[0], 0.404166, 1.450000);
TextDrawTextSize(UI[0], 400.000000, 17.000000);
TextDrawSetOutline(UI[0], 1);
TextDrawSetShadow(UI[0], 0);
TextDrawAlignment(UI[0], 1);
TextDrawColor(UI[0], -1);
TextDrawBackgroundColor(UI[0], 255);
TextDrawBoxColor(UI[0], 50);
TextDrawUseBox(UI[0], 0);
TextDrawSetProportional(UI[0], 1);
TextDrawSetSelectable(UI[0], 0);

UI[1] = TextDrawCreate(269.000000, 17.000000, "State");
TextDrawFont(UI[1], 3);
TextDrawLetterSize(UI[1], 0.404166, 1.500000);
TextDrawTextSize(UI[1], 400.000000, 17.000000);
TextDrawSetOutline(UI[1], 1);
TextDrawSetShadow(UI[1], 0);
TextDrawAlignment(UI[1], 1);
TextDrawColor(UI[1], -1);
TextDrawBackgroundColor(UI[1], 255);
TextDrawBoxColor(UI[1], 50);
TextDrawUseBox(UI[1], 0);
TextDrawSetProportional(UI[1], 1);
TextDrawSetSelectable(UI[1], 0);

UI[2] = TextDrawCreate(314.000000, 17.000000, "Roleplay");
TextDrawFont(UI[2], 3);
TextDrawLetterSize(UI[2], 0.404166, 1.450000);
TextDrawTextSize(UI[2], 400.000000, 17.000000);
TextDrawSetOutline(UI[2], 1);
TextDrawSetShadow(UI[2], 0);
TextDrawAlignment(UI[2], 1);
TextDrawColor(UI[2], -1);
TextDrawBackgroundColor(UI[2], 255);
TextDrawBoxColor(UI[2], 50);
TextDrawUseBox(UI[2], 0);
TextDrawSetProportional(UI[2], 1);
TextDrawSetSelectable(UI[2], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
