/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:UI[2];

//Textdraws
UI[0] = TextDrawCreate(579.000000, 17.000000, "00:00");
TextDrawFont(UI[0], 2);
TextDrawLetterSize(UI[0], 0.370831, 1.899999);
TextDrawTextSize(UI[0], 400.000000, 17.000000);
TextDrawSetOutline(UI[0], 2);
TextDrawSetShadow(UI[0], 0);
TextDrawAlignment(UI[0], 2);
TextDrawColor(UI[0], -1);
TextDrawBackgroundColor(UI[0], 255);
TextDrawBoxColor(UI[0], 50);
TextDrawUseBox(UI[0], 0);
TextDrawSetProportional(UI[0], 1);
TextDrawSetSelectable(UI[0], 0);

UI[1] = TextDrawCreate(581.000000, 48.000000, "00.00.0000");
TextDrawFont(UI[1], 3);
TextDrawLetterSize(UI[1], 0.187498, 0.799997);
TextDrawTextSize(UI[1], 400.000000, 17.000000);
TextDrawSetOutline(UI[1], 2);
TextDrawSetShadow(UI[1], 0);
TextDrawAlignment(UI[1], 2);
TextDrawColor(UI[1], -1);
TextDrawBackgroundColor(UI[1], 255);
TextDrawBoxColor(UI[1], 50);
TextDrawUseBox(UI[1], 0);
TextDrawSetProportional(UI[1], 1);
TextDrawSetSelectable(UI[1], 0);


//Player Textdraws

/*Player Progress Bars
Requires "progress2" include by Southclaws
Download: https://github.com/Southclaws/progress2/releases */
